- name: Recopilar datos del Survey
  hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "Datos recibidos del survey: {{ parameter_type }}, {{ parameter_name }}, {{ parameter_value }} "
