---
- name: Retrieve AWS Parameter Store keys
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get all parameter store keys
      community.aws.aws_ssm_parameter_info:
        path: "/"
        recursive: true
      register: parameter_info

    - name: Set parameter list
      set_fact:
        parameter_list: "{{ parameter_info.parameters | map(attribute='name') | list }}"

    - name: Show parameter list
      debug:
        msg: "{{ parameter_list }}"
