- name: Create parameter in AWS Parameter Store
  hosts:  localhost
  gather_facts: false

 # vars:
 #   parameter_name: "token2"
 #   parameter_value: "12345678"
 #   parameter_type: "SecureString"

  tasks:
    - name: Create parameter in AWS Parameter Store 
      community.aws.aws_ssm_parameter_store:
        name: "{{ parameter_name }}"
        value: "{{ parameter_value }}"
        type: "SecureString"
        overwrite_value: always
      register: result
    
    - name: Result print
      debug:
        var: result
