---
- name: Mostrar directorio actual
  hosts: localhost
  gather_facts: no  # Opcional, si no necesitas facts
  tasks:
    - name: Mostrar directorio actual
      ansible.builtin.command: "pwd"
      register: current_directory

    - debug:
        var: current_directory.stdout

- name: Setup - Instalar roles y colecciones de Galaxy
  hosts: localhost
  gather_facts: no  # Opcional
  tasks:
    - name: Instalar roles desde requirements.yml
      ansible.builtin.command: "ansible-galaxy install -r /runner/project/requirements.yml"
      changed_when: false

    - name: Instalar colecciones desde requirements.yml
      ansible.builtin.command: "ansible-galaxy collection install -r /runner/project/requirements.yml"
      changed_when: false
